-- DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
	id BIGINT ( 15 ) NOT NULL AUTO_INCREMENT COMMENT '用户Id（主键）',
	user_name VARCHAR ( 50 ) NOT NULL DEFAULT '' COMMENT '用户名',
	`password` VARCHAR ( 50 ) NOT NULL DEFAULT '' COMMENT '密码',
	sex VARCHAR ( 50 ) NOT NULL DEFAULT '' COMMENT '性别',
PRIMARY KEY ( id )
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COMMENT 'user';