# 设置服务名
spring:
  application:
    name: hello-service

# 设置服务信息    
server:
  port: 7001

# 设置注册中心地址  
eureka:
  client:   
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8001/eureka/,http://localhost:8003/eureka/