server:
  port: ${random.init[10000,19999]}
mybatis:
  type-aliases-package: aaron.springbootmybatisannotation.entity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springquickstart?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
