mybatis:
  type-aliases-package: aaron.springbootmybatis.model
spring:  datasource:    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver